export default {
  autosize: true,
  interval: "D",
  timezone: "Etc/UTC",
  theme: "dark",
  style: "1",
  locale: "en",
  enable_publishing: false,
  backgroundColor: "rgba(0, 0, 0, 1)",
  withdateranges: true,
  hide_side_toolbar: false,
  allow_symbol_change: true,
  details: true,
  show_popup_button: true,
  popup_width: "1000",
  popup_height: "650",
  container_id: "tradingview_9f82c",
};
